/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=server/wrangler.jsonc --include-runtime=false server/worker-configuration.d.ts` (hash: 5cfe94fee94e40df796109e48f68f651)
interface __BaseEnv_Env {
	ROOM: DurableObjectNamespace<import("./worker/index").Room>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "Room";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
