/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=server/wrangler.jsonc --include-runtime=false --strict-vars=false server/worker-configuration.d.ts` (hash: e7a1631a225c53a7ce27595a3069cd81)
interface __BaseEnv_Env {
	RELAY_ATTEMPT_LIMIT: string;
	ROOM: DurableObjectNamespace<import("./worker/index").Room>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "Room";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
