#!/usr/bin/env python3
"""Build the meal-occasion filter table (ADR-0043) from builder_data.json.

The catalog DOES carry a meal-occasion field: `variant_meta[].ruleset`, whose
values are dinner | simple | breakfast | dessert | snack | cpg. That is the
same taxonomy the Mealime app filters on (its "Breakfast 151" is exactly this
field), so the app reads it directly — no keyword lens, no per-recipe parsing,
no client-side scan of 2,730 variants.

This script only COUNTS that field (one pass over variant_meta) and writes a
small committed artifact, public/data/recipe_types.json. The client imports the
artifact statically (Vite inlines it, like ingredients.json), so the dropdown
costs one tiny module at runtime, while the FACET itself is an exact string
compare against `meta.ruleset`, already present in the loaded catalog.

`cpg` (cost-per-gram, Mealime's product-placement recipes) is emitted for count
parity but NOT offered as an occasion: it is an advertising bucket, not a meal.
Every other bucket is a meal type the household plans around.

    python3 scripts/extract_recipe_types.py [--check]

`--check` verifies the committed artifact matches a fresh build (exit 1 on
drift) without rewriting it, for CI.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

BUILDER = os.path.join(ROOT, "public/data/builder_data.json")
OUT = os.path.join(ROOT, "public/data/recipe_types.json")

# (id, label, icon, ruleset) in DISPLAY order. Stable negative ids so an
# occasion can never collide with a catalog id (all variant ids are positive).
TABLE = [
    (-1, "Breakfast", "Sunrise", "breakfast"),
    (-2, "Dessert", "IceCreamCone", "dessert"),
    (-3, "Snack", "Cookie", "snack"),
    (-4, "Lunch", "Soup", "simple"),
    (-5, "Dinner", "UtensilsCrossed", "dinner"),
]

# Emitted for count parity, not offered as a filter option (ADR-0043 cpg note).
NON_OCCASION = [(-6, "Branded", "Tag", "cpg")]

ALL_ROWS = TABLE + NON_OCCASION
OFFERED_IDS = {row[0] for row in TABLE}


def user_recipe_entries():
    """(id, {meta, doc, addedAt, source}) for each household recipe."""
    with open(os.path.join(ROOT, "public/data/user_recipes.json"), encoding="utf-8") as f:
        payload = json.load(f)
    out = []
    for entry in payload.get("recipes") or []:
        out.append(((entry.get("meta") or {}).get("id"), entry))
    return [pair for pair in out if pair[0] is not None]


def build():
    with open(BUILDER) as f:
        builder = json.load(f)

    feasible = set(builder["feasible_variants"])
    counts = {row[0]: 0 for row in ALL_ROWS}
    by_ruleset = {row[3]: row[0] for row in ALL_ROWS}
    unmatched = 0
    seen_ids = set()

    # ADR-0054: the household's own recipes are filterable exactly like the
    # frozen catalog's (they are merged into `byId` at load), so their
    # `ruleset` has to be counted here too — a Breakfast chip that says 151
    # while the pancake is on screen and filterable would be a lie.
    for _vid, entry in user_recipe_entries():
        feasible.add(entry["meta"]["id"])
        builder["variant_meta"].append(entry["meta"])

    for meta in builder["variant_meta"]:
        vid = meta["id"]
        if vid in seen_ids:
            continue
        seen_ids.add(vid)
        # Only variants the planner can actually serve are filterable.
        if vid not in feasible:
            continue
        tid = by_ruleset.get(meta.get("ruleset"))
        if tid is None:
            unmatched += 1
        else:
            counts[tid] += 1

    by_id = {}
    for tid, label, icon, ruleset in ALL_ROWS:
        by_id[str(tid)] = {
            "id": tid,
            "label": label,
            "icon": icon,
            "ruleset": ruleset,
            "count": counts[tid],
            "offered": tid in OFFERED_IDS,
        }

    return {
        "_comment": "Generated by scripts/extract_recipe_types.py - do not edit. See ADR-0043.",
        "byId": by_id,
        "order": [row[0] for row in ALL_ROWS],
        "total": len(feasible),
        "unmatched": unmatched,
    }


def main():
    check = "--check" in sys.argv
    doc = build()

    total = doc["total"]
    summed = sum(v["count"] for v in doc["byId"].values())
    if summed + doc["unmatched"] != total:
        print(
            "PARTITION FAIL: buckets %d + unmatched %d != %d feasible variants"
            % (summed, doc["unmatched"], total)
        )
        return 1
    if doc["unmatched"]:
        print("NOTE: %d variants carry an unmapped ruleset value" % doc["unmatched"])

    # A chip the user can select must never be empty.
    for tid, label, _icon, _rs in TABLE:
        if doc["byId"][str(tid)]["count"] < 1:
            print("FAIL: occasion %s matched ZERO variants" % label)
            return 1

    payload = json.dumps(doc, indent=2, sort_keys=True) + "\n"

    if check:
        if not os.path.exists(OUT):
            print("CHECK FAIL: %s missing" % OUT)
            return 1
        with open(OUT) as f:
            if f.read() != payload:
                print("CHECK FAIL: committed recipe_types.json is stale")
                return 1
        print("check ok: recipe_types.json is current")
        return 0

    with open(OUT, "w") as f:
        f.write(payload)

    print("wrote %s" % os.path.relpath(OUT, ROOT))
    for tid, label, _icon, _rs in ALL_ROWS:
        v = doc["byId"][str(tid)]
        print("  %-10s %5d%s" % (v["label"], v["count"], "" if v["offered"] else "   (not offered)"))
    print("  %-10s %5d" % ("TOTAL", total))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
